# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "tuong-currency"
client_id = "bf28e1a0d1bd3a6b501db9043b10df61"
application_url = "https://cathedral-smart-heard-semiconductor.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_customers,write_customers,read_discounts,write_discounts,read_draft_orders,write_draft_orders,read_files,write_files,read_fulfillments,write_fulfillments,read_gdpr_data_request,read_gift_cards,write_gift_cards,read_inventory,write_inventory,read_legal_policies,write_legal_policies,read_locations,read_marketing_events,write_marketing_events,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_online_store_navigation,read_online_store_pages,write_online_store_pages,read_order_edits,write_order_edits,read_orders,write_orders,read_price_rules,write_price_rules,read_products,write_products,read_product_listings,write_product_listings,read_reports,write_reports,read_resource_feedbacks,write_resource_feedbacks,read_shipping,write_shipping,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,read_content,write_content,read_themes,write_themes,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_translations,write_translations"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://cathedral-smart-heard-semiconductor.trycloudflare.com/auth/callback",
  "https://cathedral-smart-heard-semiconductor.trycloudflare.com/auth/shopify/callback",
  "https://cathedral-smart-heard-semiconductor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2021-10"

[pos]
embedded = false

[app_preferences]
url = "https://dev-currency.herokuapp.com/"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lemanhtuong.myshopify.com"
